name: filip_mcp
description: Filip's own bespoke MCP server.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  async: ^2.13.0
  dart_mcp: ^0.3.0
  logging: ^1.2.0
  meta: ^1.17.0
  path: ^1.9.1
  stream_channel: ^2.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
